host: lvh.me
port: 8080
dev: true
projectsPerPage: 20
organisationsPerPage: 20
maxLogoSize: 1048576
sessionSecret: mrzmm3GbksRN2bAhKA25YDZDm-lze7JGuTR3j81RC80=
db:
  host: localhost
  port: 5432
  database: fossfund
  user: fossfund
  pass:
jinja:
  trim_blocks: true
  lstrip_blocks: true
  autoescape: true
oauthProviders:
  github:
    client: GithubClient
    options:
      client_id: a8f697855b0ca120e0e8
      client_secret: 0ecd528baefcf83f6157345cfaf0b8fcf7787c62
  bitbucket:
    client: Bitbucket2Client
    options:
      client_id: pEq8fSwMNAfYNMvXW5
      client_secret: v3kcd58EWzADtECG5VJy9Mc9FbqqmnUM
  google:
    client: GoogleClient
    options:
      client_key:
      client_secret:
urlTypes:
  patreon:
    format: https://www.patreon.com/%s
  paypal:
    format: https://www.paypal.me/%s
  bountysource:
    format: https://www.bountysource.com/teams/%s
