host: 127.0.0.1
port: 8080
dev: true
softwaresPerPage: 20
db:
  host: localhost
  port: 5432
  database: fossfund
  user: fossfund
  pass:
jinja:
  trim_blocks: true
  lstrip_blocks: true
  autoescape: true
